### ISSUE TITLE
can't create valid licenses

### ISSUE THREAD

**Issue by seppy87** [abumq/licensepp#29]
I have made a test license which first decodes JSON is. The Signature is an empty string 
`{"authority_signature":"","expiry_date":1612447411,"issue_date":1580911411`

and validating the file fails with:
Failed to verify the licensing authority

**Comment by michaelmigliore** [comment]
In case someone has the same problem, it's coming from a bug in the copy constructor of `License` class. It has been fixed here: https://github.com/amrayn/licensepp/commit/cd4706f4d6b4056f49c24db657d9af2c633396f0
