### ISSUE TITLE
Question about usage!

### ISSUE THREAD

**Issue by diuming** [abumq/licensepp#31]
i have been success compiled this library on macOS.
but, I have an usage question.

Does it can be work like this [behavior](https://www.codeproject.com/articles/8902/a-simple-software-key-useful-to-protect-software-c?fid=130916&df=90&mpp=25&prof=True&sort=Position&view=Normal&spc=Relaxed&fr=26).
if so, could you give me a hint?

thanks

**Comment by abumusamq** [comment]
@diuming could you please simplify your question and write it in a line or two?

**Comment by diuming** [comment]
@abumusamq thanks for replaying

ex:

```
 Client
+--------------+
| Application  +---> USB instrument(serial number)
+--------------+
| public key   |      
| private key? | 
| licensed?    |
+--------------+
1)using the serial number to create an unique public key in memory(also can save to a file).
2)send public key to Vendor(now the licensed = false). take a look vendor, please
3)receive the unique private key.
4)verify public key and private key are match?
5)if so, the licensed = true (Application can work)
```
```
Venor
1)receive the public key.
2)create an unique private key.
3)sent to client.
```

**Comment by lurumdare** [comment]
@diuming see another libs

akio-tanaka/lickey
open-license-manager

**Comment by diuming** [comment]
@lurumdare but it does not support macOS.

**Comment by abumq** [comment]
It does support macOS. I have built it on macOS (both Intel and ARM64), Linux (x86_64 and ARM64) and Windows

I am not sure if this is relevant now but I am going to close this and feel free to open a new one if this helps.
